### ISSUE TITLE
Add Crestron-Fonts to Readme

### ISSUE THREAD

**Issue by alvaroyurrita** [purebordem/Crestron-Community-Resources#7]
I created a github/npm library where I took the SmartGrpahics Theme Transport Icons and converted them into vectorized fonts.  Now it is easy to use these fonts to convert previously created VTP projects into HTML projects.

Can you add the following to the Font-End section:

### Community Modules
* [Crestron-Fonts](https://github.com/alvaroyurrita/Crestron-Fonts)
  * SmartGraphics Theme Transport Icons turned into Vectorized Fonts. Can be infinitely enlarged, rotated, colored, animated etc. using CSS styles.

**Comment by purebordem** [comment]
Done and added, thanks!
