### ISSUE TITLE
Please add my new Vue examples

### ISSUE THREAD

**Issue by jeffderek** [purebordem/Crestron-Community-Resources#9]
Would appreciate the add of these two examples, both designed to show how to use Vue with CrComLib without CH5 elements

https://github.com/jeffderek/crestron-vue-websocket-example
https://github.com/jeffderek/crestron-vue-simpl-example

It may also be worth noting that the two existing Vue examples are both for Vue 2, and these examples are both for Vue 3

**Comment by purebordem** [comment]
Added to the examples section, thanks!
